// Generated by Selenium IDE
import org.junit.Test;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

public class MyTest extends TestBase {

    @Test
    public void publishPostTest() {
        login();
        PostData post = new PostData("Hi!");
        applicatonManager.getPostHelper().publishPost(post);
    }

    @Test
    public void postInGroupTest() {
        login();
        PostData postDataInGroup = new PostData("New post in group now!!!!!!!!!!");
        applicatonManager.getNavigationHelper().openGroupPage();
        applicatonManager.getGroupHelper().testPostInGroup(postDataInGroup);
    }

    public void login() {

        File file = new File("/home/yuliya/IdeaProjects/myworldtest/src/main/resources/properties.properties");
        Properties p = new Properties();
        try {
            p.load(new FileReader(file));
        } catch (IOException e) {
            e.printStackTrace();
        }

        AccountData user = new AccountData(p.getProperty("login"), p.getProperty("pass"));
        applicatonManager.getNavigationHelper().openHomePage();
        applicatonManager.getLoginHelper().login(user);
    }

}